export default en = {
  giris_yap: "Giriş yap",
  anasayfa: "Anasayfa",
  hesap_ozeti: "Hesap Özeti",
  bize_ulas: "Bize Ulaş",
  cikis_yap: "Çıkış Yap",
  teklif_ver_para_kazan: "Teklif Ver Para Kazan",
  kartlarim: "Kartlarım",
  uyeligi_uzat: "Üyeliği Uzat",
  kullanici_kodu: "Kullanıcı Kodu",
  kasadaki_tutar: "Kasadaki Tutar",
  text_1: "Hizmet almak için lütfen giriş yapın veya kayıt olun.",
  text_2: "Kayıt ol",
  text_3:
    "Şimdilik usta üyeliği ile hizmet talebi alamıyoruz. Lütfen kişisel hesabınız ile kayıt olunuz.",
  text_4: "Servis oluşturmak için camera izni vermelisiniz.",
  text_5:
    "Adres için konumunuza ulaşılamadı. İnternet bağlantınızı kontrol edin veya tekrar deneyiniz.",
  text_6: "Tamam",
  text_7: "Farklı bir görsel seçiniz",
  text_8:
    "İşlem sırasında bir hata oluştur. İnternet bağlantınızı kontrol ediniz.",
  text_9:
    "Adres için konumunuza ulaşılamadı. İnternet bağlantınızı kontrol edin veya tekrar deneyiniz.",
  text_10: "Devam edebilmek için sözleşmeleri onaylamalısınız",
  text_11: "Hizmet başlığını daha açıklayıcı yazınız",
  text_12: "Hizmet notunuzu daha açıklayıcı yazınız",
  text_13: "En az bir haberleşme yöntemi seçiniz",
  text_14: "Adresiniz çok uzun kontrol ediniz",
  text_15: "Cevabınız çok kısa lütfen cevabınızı control ediniz",
  text_16: "Cevabınız çok uzun lütfen cevabınızı control ediniz",
  text_17: "Cevabınızı istenilen aralıkta giriniz",
  text_18: "Tarih seçimi hatalı. Lütfen kontrol ediniz",
  text_19: "Zorunlu seçmeli soru cevaplanmamış",
  text_20: "{{v}} sorusu boş geçilemez",
  text_21: "{{v}} sorusu için en fazla {{v1}} en az {{v2}} seçim yapmalısınız",
  text_22:
    "Hizmet oluşturulamadı. Lütfen tekrar deneyiniz ve internet bağlantınız kontrol ediniz.",
  text_23: "Size ne yakın konumdaki ustalarımıza bildirim gönderildi.",
  text_24:
    "İşlem sırasında tanımlanamayan bir hata oluştu. İnternet bağlantınızı kontrol ediniz.",
  text_25: "Okudum Onaylıyorum",
  text_26:
    "Sizlere daha iyi ve guvenilir hizmet verebilmek adina sözleşmeleri okuyunuz.",
  text_27: "Tamamla",
  text_28: "İleri",
  text_29: "Hizmet Başlığı",
  text_30: "Hizmet Notu",
  text_31:
    "Hizmetiniz ile ilgili gelismelerden nasil haberdar olmak istersiniz?",
  text_32: "** En az bir seçim yapiniz",
  text_33: "Hizmetiniz Ile Ilgili Fotograf Ekleyin",
  text_34: "Hizmetinizi Filtreleyin",
  text_35: "Kesif Istiyorum",
  text_36: "Hizmeti ustalazim garantörlügünde almak istiyorum",
  text_37: "Adresiniz",
  text_38:
    "Lütfen geçerli bir değer giriniz. En fazla : {{v1}}, En az : {{v2}}",
  text_39: "Lütfen bir seçim yapınız",
  text_40: "Hizmet ara",
  text_41: "Ara",
  text_42: "Teklif ver{\n}Para kazan",
  text_43: "Hizmet al",
  text_44: "POPÜLER KATEGORİLER",
  text_45: "Teklif onaylandı ve ustaya bilgi verildi.",
  text_46:
    "Teklif onaylama başarısız. Lütfen internet bağlantınızı kontrol ediniz.",
  text_47: "Gelen Teklifler",
  text_48: "Teklif Listesi",
  text_49: "Teklif Detayı",
  text_50: "Teklif Verebilecekler",
  text_51: "Uyarı",
  text_52: "Öncelikle giriş yapmalısınız",
  text_53: "120 saniye içinde QR kod okutulmalıdır. Yeni bir kod talep ediniz.",
  text_54:
    "QR kod oluşturulamadı. Lütfen internet bağlantınızı kontrol ediniz.",
  text_55: "Verdiğiniz puanlar çok değerli. Size daha iyi hizmet veriyoruz.",
  text_56: "İşlem sırasında hata oluştu. İnternet bağlantınızı kontrol ediniz.",
  text_57: "Hizmet onayı",
  text_58:
    "Hizmet onayı verdiğiniz an anlaşma tutarı kasanızdan düşülecek ve ustamıza iletilecektir. Hizmetin başarıyla tamamlandığını onaylıyor musunuz?",
  text_59: "Hizmet sırasında sorun ile karşılaştım",
  text_60: "Hizmet başarıyla tamamlandı",
  text_61: "Hizmet onaylama işlemi başarılı.",
  text_62:
    "Hizmet onaylama işlemi başarısız. İnternet bağlantınızı kontrol ediniz.",
  text_63: "Şikayet konusu seçiniz.",
  text_64: "Şikayet metniniz 30 ile 1000 karakter arasında olmalıdır.",
  text_65:
    "Şikayetiniz iletildi. En kısa zamanda sizin ile iletişime geçeceğiz.",
  text_66: "Şikayet iletilemedi. İnternet bağlantınızı kontrol ediniz.",
  text_67: "Hizmeti iptal etmek istediğinize emin misiniz?",
  text_68: "Hayır",
  text_69: "Evet",
  text_70: "İptal işlemi başarılı.",
  text_71: "İptal işlemi başarısız. İnternet bağlantınızı kontrol ediniz.",
  text_72: "Gelen Teklifler",
  text_73: "Tamamlanmayı Bekleyenler",
  text_74: "Onay Bekleyenler",
  text_75: "Gelen Teklifler",
  text_76: "İptal Edilenler",
  text_77: "Bekleyenler",
  text_78: "Tamamlananlar",
  text_79: "Hizmet Listesi",
  text_80: "Qr Code",
  text_81: "Puan Ver",
  text_82: "Şikayet Et",
  text_83: "Hizmet Önizleme",
  text_84: "Güncelleme işlemi başarıyla tamamlandı.",
  text_85: "Güncelleme işlemi başarısız.",
  text_86: "Hesap Bilgileriniz",
  text_87: "Kullanıcı Adı",
  text_88: "E-Posta Adresiniz",
  text_89: "Telefon Numaranız",
  text_90: "Parolanız",
  text_91:
    "Parolanız şifrelenmiştir. Bu alanı şifre değişikliği istemiyorsanız güncellemeyin.",
  text_92: "Bildirim Yönetiminiz",
  text_93: "Email ile bildirim",
  text_94: "Sms ile bildirim",
  text_95: "Sms ve email ile bildirim",
  text_96: "Bülten Aboneliği",
  text_97: "Hesap Bilgilerimi Kaydet",
  text_98: "Kullanıcı Bilgileriniz",
  text_99: "Adınız",
  text_100: "Soyadınız",
  text_101: "Kullanıcı Bilgilerimi Kaydet",
  text_102: "Cevap",
  text_103: "Net teklif",
  text_104: "Ortalama teklif",
  text_105: "Keşif için onayla",
  text_106: "Teklif daha önce onaylanmış",
  text_107: "Ustaya mesaj gönder",
  text_108: "Teklifi onayla ve ödemeyi yap",
  text_109: "Geri dön",
  text_110: "Teklif",
  text_111: "Yetkili",
  text_112: "Profili gör",
  text_113: "Teklifi incele",
  text_114:
    "Ustamız Hizmeti Onayladığında Sizde Onay Vererek Ücreti Ustamızın Hesabına Aktarabilirsiniz. Ustamız İlgili Hizmeti Onayladığında Hizmet 'Onay Bekleyenler' Adımına Geçecektir.",
  text_115: "{{v}} saniye içinde okutulmalıdır.",
  text_116: "İşlem tamamlandı",
  text_117: "Adres Açıklaması",
  text_118: "Garantörlü mü?",
  text_119: "Müşteri onaydı mı?",
  text_120: "Usta onayladı mı?",
  text_121: "Keşif istendi mi?",
  text_122: "Ödeme yapıldı mı?",
  text_123: "İptal edildi mi?",
  text_124: "Ülke / İl / İlçe / Mahalle",
  text_125: "Kapat",
  text_126:
    "Hizmetinizi daha önce puanlamışsınız. Verdiğiniz puanlar hizmet kalitemiz için çok önemlidir.",
  text_127:
    "Firma daha önce puanlanmamış hemen firma hakkındaki görüşlerinizi müşterilerimiz ile paylaşarak hizmet kalitemizi arttırmamıza yardımcı olun.",
  text_128: "Gönder",
  text_129: "İncele",
  text_130: "İptal et",
  text_131: "Hizmeti onayla",
  text_132: "Usta onayı için QR oluştur",
  text_133: "Teklifleri gör",
  text_134: "Hizmetlerim",
  text_135: "Şikayet Konusu",
  text_136: "Seçiniz",
  text_137: "Şikayetiniz",
  text_138: "Şikayet Mesajını Gönder",
  text_139: "Oran",
  text_140: "Teklif talep et",
  text_141: "Lütfen bir mesaj konusu seçiniz",
  text_142: "Alanları kontrol ediniz",
  text_143: "Mesajınız iletildi. En yakın zamanda size geri dönüş yapacağız.",
  text_144: "Üzgünüz mesajınız gönderilemedi. Lütfen tekrar deneyiniz.",
  text_145: "Mesaj Konusu",
  text_146: "(Zorunlu)",
  text_147: "Adınız Soyadınız",
  text_148: "Telefon Numaranız",
  text_149: "Mail Adresiniz",
  text_150: "Mesaj Başlığınız",
  text_151: "Mesajınız",
  text_152: "Teklifinizi kontrol ediniz.",
  text_153: "Teklifiniz güncellendi.",
  text_154: "Teklifiniz güncellenirken hata oluştu. Tekrar deneyiniz.",
  text_155: "Kodu okutmak için kamera erişim izni vermelisiniz.",
  text_156:
    "Kod oluşturulduktan sonra 2 dakika içinde okutulmalıdır. Lütfen müşterinizden yeni bir kod oluşturmasını isteyiniz.",
  text_157: "Kod bulunamadı. Lütfen Tekrar Deneyiniz.",
  text_158:
    "İşlem başarılı. Size hizmeti onaylayarak ücret transferini gerçekleştirebilirsiniz.",
  text_159: "Teklif Güncelleme",
  text_160: "Yeni teklifinizi yazınız.",
  text_161: "Sayısal Değer Giriniz.",
  text_162: "Teklifi güncelle",
  text_163: "QR ile hizmet onaylama",
  text_164: "Teklifiniz geçersiz. Lütfen kontrol ediniz.",
  text_165: "Lütfen cevabı istenilen aralıkta giriniz.",
  text_166: "Zorunlu alan.",
  text_167: "Lütfen seçimleri kontrol ediniz.",
  text_168: "Teklifinizi ve sorulara verdiğiniz cevapları kontrol ediniz.",
  text_169: "Teklifiniz başarıyla kaydedildi ve müşteriye bilgi verildi.",
  text_170:
    "Teklifiniz kaydedilemedi. Lütfen internet bağlantınızı kontrol ediniz.",
  text_171: "Hizmetler",
  text_172: "Hizmet Detay",
  text_173: "Teklif Ver",
  text_174: "Hizmet Adresi",
  text_175: "Adres Detayı",
  text_176: "İlgili Hizmetin Soruları ve Cevapları",
  text_177: "İlgili Hizmetin Müşteri Tarafından Alınan Resimleri",
  text_178: "Teklifiniz",
  text_179: "En fazla {{v1}} karakter. En az {{v2}} karakter giriniz.",
  text_180: "En yüksek",
  text_181: "En düşük",
  text_182: "{{v}} TL teklif verildi Detayları incele",
  text_183: "Onayla ve tamamla",
  text_184: "Sorulara verilen cevaplar",
  text_185: "En az {{v}} karakter yazmalısınız.",
  text_186: "Mesajınız gönderilemedi. Tekrar deneyiniz.",
  text_187: "Mesajlar Yüklenemedi",
  text_188: "yazıyor...",
  text_189: "Sohbetler",
  text_190: "LET'S GET STARTED",
  text_191: "Usta Arıyorum",
  text_192: "sosyal medya ile kayıt ol",
  text_193: "Hesabın var mı?",
  text_194: "ile",
  text_195: "ÜYELİK TİPİ SEÇİNİZ",
  text_196: "Mail adresi kullanımda. Giriş sayfasına yönlendiriliyorsunuz",
  text_197:
    "Kayıt işleminiz tamamlandı. {{v}} ile kayıt olduğunuz için öyeliğiniz otomatik onaylandı.",
  text_198: "Üyelik bulunamadı. Lütfen ilk önce üye olunuz.",
  text_199: "Üyelik aktivasyonu geçersiz. Lütfen üyeliğiniz aktif ediniz.",
  text_200:
    "Bu üyelik sosyal medya hesabı ile kayıt olmamıştır. Lütfen şifreniz ile giriş yapınız."
};
