export const GET_CATEGORIES_AND_SUBCATEGORIES =
  "HOME_SCREEN/GET_CATEGORIES_AND_SUBCATEGORIES/LOAD";
export const GET_CATEGORIES_AND_SUBCATEGORIES_SUCCESS =
  "HOME_SCREEN/GET_CATEGORIES_AND_SUBCATEGORIES/LOAD_SUCCESS";
export const GET_CATEGORIES_AND_SUBCATEGORIES_FAIL =
  "HOME_SCREEN/GET_CATEGORIES_AND_SUBCATEGORIES/LOAD_FAIL";
export const GET_CATEGORIES_AND_SUBCATEGORIES_URL =
  "/CategoryService/AllCategoriesAndSubCategories";
