export const GET_COMPANY_SERVICE_PREVIEW =
  "COMPANY_SERVICE_SCREEN/GET_COMPANY_SERVICE_PREVIEW/LOAD";
export const GET_COMPANY_SERVICE_PREVIEW_SUCCESS =
  "COMPANY_SERVICE_SCREEN/GET_COMPANY_SERVICE_PREVIEW/LOAD_SUCCESS";
export const GET_COMPANY_SERVICE_PREVIEW_FAIL =
  "COMPANY_SERVICE_SCREEN/GET_COMPANY_SERVICE_PREVIEW/LOAD_FAIL";
export const GET_COMPANY_SERVICE_PREVIEW_URL =
  "/CompanyDetailService/ServicePreviewView";

export const GET_SERVICE_PREVIEW_DETAIL =
  "ALL_SCREEN/GET_SERVICE_PREVIEW_DETAIL/LOAD";
export const GET_SERVICE_PREVIEW_DETAIL_SUCCESS =
  "ALL_SCREEN/GET_SERVICE_PREVIEW_DETAIL/LOAD_SUCCESS";
export const GET_SERVICE_PREVIEW_DETAIL_FAIL =
  "ALL_SCREEN/GET_SERVICE_PREVIEW_DETAIL/LOAD_FAIL";
export const GET_SERVICE_PREVIEW_DETAIL_URL =
  "/CustomerDetailService/servicePreviewObjs";

export const GET_COMPANY_SERVICE_RATE =
  "ALL_SCREEN/GET_COMPANY_SERVICE_RATE/LOAD";
export const GET_COMPANY_SERVICE_RATE_SUCCESS =
  "ALL_SCREEN/GET_COMPANY_SERVICE_RATE/LOAD_SUCCESS";
export const GET_COMPANY_SERVICE_RATE_FAIL =
  "ALL_SCREEN/GET_COMPANY_SERVICE_RATE/LOAD_FAIL";
export const GET_COMPANY_SERVICE_RATE_URL =
  "/CompanyDetailService/CompanyServiceRate";

export const GET_CUSTOMER_SERVICE_IS_POINT =
  "ALL_SCREEN/GET_CUSTOMER_SERVICE_IS_POINT/LOAD";
export const GET_CUSTOMER_SERVICE_IS_POINT_SUCCESS =
  "ALL_SCREEN/GET_CUSTOMER_SERVICE_IS_POINT/LOAD_SUCCESS";
export const GET_CUSTOMER_SERVICE_IS_POINT_FAIL =
  "ALL_SCREEN/GET_CUSTOMER_SERVICE_IS_POINT/LOAD_FAIL";
export const GET_CUSTOMER_SERVICE_IS_POINT_URL =
  "/CompanyDetailService/CustomerServiceIsPoint";

export const GET_CUSTOMER_SERVICE_OLD_POINT =
  "ALL_SCREEN/GET_CUSTOMER_SERVICE_OLD_POINT/LOAD";
export const GET_CUSTOMER_SERVICE_OLD_POINT_SUCCESS =
  "ALL_SCREEN/GET_CUSTOMER_SERVICE_OLD_POINT/LOAD_SUCCESS";
export const GET_CUSTOMER_SERVICE_OLD_POINT_FAIL =
  "ALL_SCREEN/GET_CUSTOMER_SERVICE_OLD_POINT/LOAD_FAIL";
export const GET_CUSTOMER_SERVICE_OLD_POINT_URL =
  "/CompanyDetailService/CustomerServiceOldPoint";

export const GET_SERVICE_POINT_LIST = "ALL_SCREEN/GET_SERVICE_POINT_LIST/LOAD";
export const GET_SERVICE_POINT_LIST_SUCCESS =
  "ALL_SCREEN/GET_SERVICE_POINT_LIST/LOAD_SUCCESS";
export const GET_SERVICE_POINT_LIST_FAIL =
  "ALL_SCREEN/GET_SERVICE_POINT_LIST/LOAD_FAIL";
export const GET_SERVICE_POINT_LIST_URL =
  "/CompanyDetailService/ServicePointList";
