export const GET_COMPANY_SERVICE_PREVIVEW =
  "COMPANY_SERVICE_SCREEN/GET_COMPANY_SERVICE_PREVIVEW/LOAD";
export const GET_COMPANY_SERVICE_PREVIVEW_SUCCESS =
  "COMPANY_SERVICE_SCREEN/GET_COMPANY_SERVICE_PREVIVEW/LOAD_SUCCESS";
export const GET_COMPANY_SERVICE_PREVIVEW_FAIL =
  "COMPANY_SERVICE_SCREEN/GET_COMPANY_SERVICE_PREVIVEW/LOAD_FAIL";
export const GET_COMPANY_SERVICE_PREVIVEW_URL =
  "/CompanyDetailService/CompanyServicePreviewView";

export const GET_SERVICE_PREVIEW_DETAIL =
  "ALL_SCREEN/GET_SERVICE_PREVIEW_DETAIL/LOAD";
export const GET_SERVICE_PREVIEW_DETAIL_SUCCESS =
  "ALL_SCREEN/GET_SERVICE_PREVIEW_DETAIL/LOAD_SUCCESS";
export const GET_SERVICE_PREVIEW_DETAIL_FAIL =
  "ALL_SCREEN/GET_SERVICE_PREVIEW_DETAIL/LOAD_FAIL";
export const GET_SERVICE_PREVIEW_DETAIL_URL =
  "/CustomerDetailService/servicePreviewObjs";
