export const GET_CUSTOMER_SERVICE_COUNT =
  "CUSTOMER_DETAIL_SCREEN/GET_CUSTOMER_SERVICE_COUNT/LOAD";
export const GET_CUSTOMER_SERVICE_COUNT_SUCCESS =
  "CUSTOMER_DETAIL_SCREEN/GET_CUSTOMER_SERVICE_COUNT/LOAD_SUCCESS";
export const GET_CUSTOMER_SERVICE_COUNT_FAIL =
  "CUSTOMER_DETAIL_SCREEN/GET_CUSTOMER_SERVICE_COUNT/LOAD_FAIL";
export const GET_CUSTOMER_SERVICE_COUNT_URL =
  "/CustomerDetailService/CustomerServiceCount";

export const SET_USER_UPDATE =
  "CUSTOMER_DETAIL_PROFILE_SCREEN/SET_USER_UPDATE/LOAD";
export const SET_USER_UPDATE_SUCCESS =
  "CUSTOMER_DETAIL_PROFILE_SCREEN/SET_USER_UPDATE/LOAD_SUCCESS";
export const SET_USER_UPDATE_FAIL =
  "CUSTOMER_DETAIL_PROFILE_SCREEN/SET_USER_UPDATE/LOAD_FAIL";
export const SET_USER_UPDATE_URL = "/CustomerDetailService/editUserInformation";

export const SET_CUSTOMER_UPDATE =
  "CUSTOMER_DETAIL_PROFILE_SCREEN/SET_CUSTOMER_UPDATE/LOAD";
export const SET_CUSTOMER_UPDATE_SUCCESS =
  "CUSTOMER_DETAIL_PROFILE_SCREEN/SET_CUSTOMER_UPDATE/LOAD_SUCCESS";
export const SET_CUSTOMER_UPDATE_FAIL =
  "CUSTOMER_DETAIL_PROFILE_SCREEN/SET_CUSTOMER_UPDATE/LOAD_FAIL";
export const SET_CUSTOMER_UPDATE_URL =
  "/CustomerDetailService/editCustomerInformation";
