export const GET_CUSTOMER_SERVICE_COUNT =
  "CUSTOMER_DETAIL_SCREEN/GET_CUSTOMER_SERVICE_COUNT/LOAD";
export const GET_CUSTOMER_SERVICE_COUNT_SUCCESS =
  "CUSTOMER_DETAIL_SCREEN/GET_CUSTOMER_SERVICE_COUNT/LOAD_SUCCESS";
export const GET_CUSTOMER_SERVICE_COUNT_FAIL =
  "CUSTOMER_DETAIL_SCREEN/GET_CUSTOMER_SERVICE_COUNT/LOAD_FAIL";
export const GET_CUSTOMER_SERVICE_COUNT_URL =
  "/CustomerDetailService/CustomerServiceCountPreview";

export const SET_USER_UPDATE =
  "CUSTOMER_DETAIL_PROFILE_SCREEN/SET_USER_UPDATE/LOAD";
export const SET_USER_UPDATE_SUCCESS =
  "CUSTOMER_DETAIL_PROFILE_SCREEN/SET_USER_UPDATE/LOAD_SUCCESS";
export const SET_USER_UPDATE_FAIL =
  "CUSTOMER_DETAIL_PROFILE_SCREEN/SET_USER_UPDATE/LOAD_FAIL";
export const SET_USER_UPDATE_URL = "/CustomerDetailService/editUserInformation";

export const GET_CUSTOMER_SERVICE_PREVIEW =
  "CUSTOMER_SERVICE_SCREEN/GET_CUSTOMER_SERVICE_PREVIEW/LOAD";
export const GET_CUSTOMER_SERVICE_PREVIEW_SUCCESS =
  "CUSTOMER_SERVICE_SCREEN/GET_CUSTOMER_SERVICE_PREVIEW/LOAD_SUCCESS";
export const GET_CUSTOMER_SERVICE_PREVIEW_FAIL =
  "CUSTOMER_SERVICE_SCREEN/GET_CUSTOMER_SERVICE_PREVIEW/LOAD_FAIL";
export const GET_CUSTOMER_SERVICE_PREVIEW_URL =
  "/CustomerDetailService/ServicePreviewView";

export const SET_CUSTOMER_UPDATE =
  "CUSTOMER_DETAIL_PROFILE_SCREEN/SET_CUSTOMER_UPDATE/LOAD";
export const SET_CUSTOMER_UPDATE_SUCCESS =
  "CUSTOMER_DETAIL_PROFILE_SCREEN/SET_CUSTOMER_UPDATE/LOAD_SUCCESS";
export const SET_CUSTOMER_UPDATE_FAIL =
  "CUSTOMER_DETAIL_PROFILE_SCREEN/SET_CUSTOMER_UPDATE/LOAD_FAIL";
export const SET_CUSTOMER_UPDATE_URL =
  "/CustomerDetailService/editCustomerInformation";

export const GET_SERVICE_PREVIEW_DETAIL_QUESTION =
  "ALL_SCREEN/GET_SERVICE_PREVIEW_DETAIL_QUESTION/LOAD";
export const GET_SERVICE_PREVIEW_DETAIL_QUESTION_SUCCESS =
  "ALL_SCREEN/GET_SERVICE_PREVIEW_DETAIL_QUESTION/LOAD_SUCCESS";
export const GET_SERVICE_PREVIEW_DETAIL_QUESTION_FAIL =
  "ALL_SCREEN/GET_SERVICE_PREVIEW_DETAIL_QUESTION/LOAD_FAIL";
export const GET_SERVICE_PREVIEW_DETAIL_QUESTION_URL =
  "/CustomerDetailService/ServiceCategoryQuestionsAndAnswers";
