export const CUSTOMER_REGISTER_POST = "CUSTOMER_REGISTER_POST/LOAD";
export const CUSTOMER_REGISTER_POST_SUCCESS =
  "CUSTOMER_REGISTER_POST/LOAD_SUCCESS";
export const CUSTOMER_REGISTER_POST_FAIL = "CUSTOMER_REGISTER_POST/LOAD_FAIL";
export const CUSTOMER_REGISTER_POST_URL = "/CustomerService/CustomerRegister";

export const MASTER_REGISTER_POST = "MASTER_REGISTER_POST/LOAD";
export const MASTER_REGISTER_POST_SUCCESS = "MASTER_REGISTER_POST/LOAD_SUCCESS";
export const MASTER_REGISTER_POST_FAIL = "MASTER_REGISTER_POST/LOAD_FAIL";
export const MASTER_REGISTER_POST_URL = "/CustomerService/MasterRegister";

export const EMAIL_VALIDATE_POST = "EMAIL_VALIDATE_POST/LOAD";
export const EMAIL_VALIDATE_POST_SUCCESS = "EMAIL_VALIDATE_POST/LOAD_SUCCESS";
export const EMAIL_VALIDATE_POST_FAIL = "EMAIL_VALIDATE_POST/LOAD_FAIL";
export const EMAIL_VALIDATE_POST_URL = "/CustomerService/EmailValidate";
