export const GET_TOKEN = "GENERAL_SETTINGS/GET_TOKEN/LOAD";
export const GET_TOKEN_SUCCESS = "GENERAL_SETTINGS/GET_TOKEN/LOAD_SUCCESS";
export const GET_TOKEN_FAIL = "GENERAL_SETTINGS/GET_TOKEN/LOAD_FAIL";
export const GET_TOKEN_URL = "/GeneralServiceGet/getToken";

export const REFRESH_AUTHENTICATION_USER =
  "ALL_SCREEN/REFRESH_AUTHENTICATION_USER/LOAD";
export const REFRESH_AUTHENTICATION_USER_SUCCESS =
  "ALL_SCREEN/REFRESH_AUTHENTICATION_USER/LOAD_SUCCESS";
export const REFRESH_AUTHENTICATION_USER_FAIL =
  "ALL_SCREEN/REFRESH_AUTHENTICATION_USER/LOAD_FAIL";
export const REFRESH_AUTHENTICATION_USER_URL =
  "/GeneralServiceGet/GetActiveUserView";

export const LOGIN_AUTHENTICATION_USER =
  "ALL_SCREEN/LOGIN_AUTHENTICATION_USER/LOAD";
export const LOGIN_AUTHENTICATION_USER_SUCCESS =
  "ALL_SCREEN/LOGIN_AUTHENTICATION_USER/LOAD_SUCCESS";
export const LOGIN_AUTHENTICATION_USER_FAIL =
  "ALL_SCREEN/LOGIN_AUTHENTICATION_USER/LOAD_FAIL";
export const LOGIN_AUTHENTICATION_USER_URL =
  "/GeneralServiceGet/GetActiveUserView";

export const GET_LANGUAGE = "ALL_SCREEN/GET_LANGUAGE/LOAD";
export const GET_LANGUAGE_SUCCESS = "ALL_SCREEN/GET_LANGUAGE/LOAD_SUCCESS";
export const GET_LANGUAGE_FAIL = "ALL_SCREEN/GET_LANGUAGE/LOAD_FAIL";
export const GET_LANGUAGE_URL = "/GeneralServiceGet/GetLanguage";

export const GET_SITE = "ALL_SCREEN/GET_SITE/LOAD";
export const GET_SITE_SUCCESS = "ALL_SCREEN/GET_SITE/LOAD_SUCCESS";
export const GET_SITE_FAIL = "ALL_SCREEN/GET_SITE/LOAD_FAIL";
export const GET_SITE_URL = "/GeneralServiceGet/GetSite";

export const GET_QR_CODE = "ALL_SCREEN/GET_QR_CODE/LOAD";
export const GET_QR_CODE_SUCCESS = "ALL_SCREEN/GET_QR_CODE/LOAD_SUCCESS";
export const GET_QR_CODE_FAIL = "ALL_SCREEN/GET_QR_CODE/LOAD_FAIL";
export const GET_QR_CODE_URL = "/GeneralServiceGet/GetQRCode";

export const GET_COMPLAINT_OPTION_LIST =
  "ALL_SCREEN/GET_COMPLAINT_OPTION_LIST/LOAD";
export const GET_COMPLAINT_OPTION_LIST_SUCCESS =
  "ALL_SCREEN/GET_COMPLAINT_OPTION_LIST/LOAD_SUCCESS";
export const GET_COMPLAINT_OPTION_LIST_FAIL =
  "ALL_SCREEN/GET_COMPLAINT_OPTION_LIST/LOAD_FAIL";
export const GET_COMPLAINT_OPTION_LIST_URL =
  "/GeneralServiceGet/ComplaintOptionList";
