export const GET_TOKEN = "GENERAL_SETTINGS/GET_TOKEN/LOAD";
export const GET_TOKEN_SUCCESS = "GENERAL_SETTINGS/GET_TOKEN/LOAD_SUCCESS";
export const GET_TOKEN_FAIL = "GENERAL_SETTINGS/GET_TOKEN/LOAD_FAIL";
export const GET_TOKEN_URL = "/GeneralServiceGet/getToken";

export const REFRESH_AUTHENTICATION_USER =
  "ALL_SCREEN/REFRESH_AUTHENTICATION_USER/LOAD";
export const REFRESH_AUTHENTICATION_USER_SUCCESS =
  "ALL_SCREEN/REFRESH_AUTHENTICATION_USER/LOAD_SUCCESS";
export const REFRESH_AUTHENTICATION_USER_FAIL =
  "ALL_SCREEN/REFRESH_AUTHENTICATION_USER/LOAD_FAIL";
export const REFRESH_AUTHENTICATION_USER_URL =
  "/GeneralServiceGet/GetActiveUserView";

export const LOGIN_AUTHENTICATION_USER =
  "ALL_SCREEN/LOGIN_AUTHENTICATION_USER/LOAD";
export const LOGIN_AUTHENTICATION_USER_SUCCESS =
  "ALL_SCREEN/LOGIN_AUTHENTICATION_USER/LOAD_SUCCESS";
export const LOGIN_AUTHENTICATION_USER_FAIL =
  "ALL_SCREEN/LOGIN_AUTHENTICATION_USER/LOAD_FAIL";
export const LOGIN_AUTHENTICATION_USER_URL =
  "/GeneralServiceGet/GetActiveUserView";
