export const GET_POPULAR_CATEGORIES = "HOME_SCREEN/POPULAR_CATEGORIES/LOAD";
export const GET_POPULAR_CATEGORIES_SUCCESS =
  "HOME_SCREEN/POPULAR_CATEGORIES/LOAD_SUCCESS";
export const GET_POPULAR_CATEGORIES_FAIL =
  "HOME_SCREEN/POPULAR_CATEGORIES/LOAD_FAIL";
export const GET_POPULAR_CATEGORIES_URL = "/HomeService/ServiceCategoryList";

export const GET_SEARCH_CATEGORIES = "HOME_SCREEN/SEARCH_CATEGORIES/LOAD";
export const GET_SEARCH_CATEGORIES_SUCCESS =
  "HOME_SCREEN/SEARCH_CATEGORIES/LOAD_SUCCESS";
export const GET_SEARCH_CATEGORIES_FAIL =
  "HOME_SCREEN/SEARCH_CATEGORIES/LOAD_FAIL";
export const GET_SEARCH_CATEGORIES_URL = "/HomeService/SearchCategory";

export const GET_CONTACT_MESSAGE_SUBJECT =
  "CONTACT_SCREEN/GET_CONTACT_MESSAGE_SUBJECT/LOAD";
export const GET_CONTACT_MESSAGE_SUBJECT_SUCCESS =
  "CONTACT_SCREEN/GET_CONTACT_MESSAGE_SUBJECT/LOAD_SUCCESS";
export const GET_CONTACT_MESSAGE_SUBJECT_FAIL =
  "CONTACT_SCREEN/GET_CONTACT_MESSAGE_SUBJECT/LOAD_FAIL";
export const GET_CONTACT_MESSAGE_SUBJECT_URL =
  "/HomeService/MessageSubjectList";

export const POST_CONTACT_MESSAGE = "CONTACT_SCREEN/POST_CONTACT_MESSAGE/LOAD";
export const POST_CONTACT_MESSAGE_SUCCESS =
  "CONTACT_SCREEN/POST_CONTACT_MESSAGE/LOAD_SUCCESS";
export const POST_CONTACT_MESSAGE_FAIL =
  "CONTACT_SCREEN/POST_CONTACT_MESSAGE/LOAD_FAIL";
export const POST_CONTACT_MESSAGE_URL = "/HomeService/AddToNewContactMessage";

export const CATEGORY_SEARCH = "CATEGORY_SEARCH/LOAD";
export const CATEGORY_SEARCH_SUCCESS = "CATEGORY_SEARCH/LOAD_SUCCESS";
export const CATEGORY_SEARCH_FAIL = "CATEGORY_SEARCH/LOAD_FAIL";
export const CATEGORY_SEARCH_URL = "/HomeService/CategorySearch";
