export const POST_ADD_OR_UPDATE_PUSH_NOTIFICATION_TOKEN =
  "PUST_ADD_OR_UPDATE_PUSH_NOTIFICATION_TOKEN/LOAD";
export const POST_ADD_OR_UPDATE_PUSH_NOTIFICATION_TOKEN_SUCCESS =
  "PUST_ADD_OR_UPDATE_PUSH_NOTIFICATION_TOKEN/LOAD_SUCCESS";
export const POST_ADD_OR_UPDATE_PUSH_NOTIFICATION_TOKEN_FAIL =
  "PUST_ADD_OR_UPDATE_PUSH_NOTIFICATION_TOKEN/LOAD_FAIL";
export const POST_ADD_OR_UPDATE_PUSH_NOTIFICATION_TOKEN_URL =
  "/api/PushNotificationTokens/AddOrUpdatePushNotificationToken";
