export const GET_SERVICE_CREATE_DATA =
  "SERVICE_SCREEN/GET_SERVICE_CREATE_DATA/LOAD";
export const GET_SERVICE_CREATE_DATA_SUCCESS =
  "SERVICE_SCREEN/GET_SERVICE_CREATE_DATA/LOAD_SUCCESS";
export const GET_SERVICE_CREATE_DATA_FAIL =
  "SERVICE_SCREEN/GET_SERVICE_CREATE_DATA/LOAD_FAIL";
export const GET_SERVICE_CREATE_DATA_URL = "/ServiceService/CategoryService";

export const SET_SERVICE_CREATE = "SERVICE_SCREEN/SET_SERVICE_CREATE/LOAD";
export const SET_SERVICE_CREATE_SUCCESS =
  "SERVICE_SCREEN/SET_SERVICE_CREATE/LOAD_SUCCESS";
export const SET_SERVICE_CREATE_FAIL =
  "SERVICE_SCREEN/SET_SERVICE_CREATE/LOAD_FAIL";
export const SET_SERVICE_CREATE_URL = "/ServiceService/CreateService";

export const SET_USER_CHAT_MESSAGE_OLD =
  "CHAT_SCREEN/SET_USER_CHAT_MESSAGE_OLD/LOAD";
export const SET_USER_CHAT_MESSAGE_OLD_SUCCESS =
  "CHAT_SCREEN/SET_USER_CHAT_MESSAGE_OLD/LOAD_SUCCESS";
export const SET_USER_CHAT_MESSAGE_OLD_FAIL =
  "CHAT_SCREEN/SET_USER_CHAT_MESSAGE_OLD/LOAD_FAIL";
export const SET_USER_CHAT_MESSAGE_OLD_URL = "/ServiceService/OldChatData";
