export const SET_SERVICE_CREATE = "SERVICE_SCREEN/SET_SERVICE_CREATE/LOAD";
export const SET_SERVICE_CREATE_SUCCESS =
  "SERVICE_SCREEN/SET_SERVICE_CREATE/LOAD_SUCCESS";
export const SET_SERVICE_CREATE_FAIL =
  "SERVICE_SCREEN/SET_SERVICE_CREATE/LOAD_FAIL";
export const SET_SERVICE_CREATE_URL = "/ServiceService/CreateService";

export const SET_SERVICE_POST_SERVICE =
  "SERVICE_SCREEN/SET_SERVICE_POST_SERVICE/LOAD";
export const SET_SERVICE_POST_SERVICE_SUCCESS =
  "SERVICE_SCREEN/SET_SERVICE_POST_SERVICE/LOAD_SUCCESS";
export const SET_SERVICE_POST_SERVICE_FAIL =
  "SERVICE_SCREEN/SET_SERVICE_POST_SERVICE/LOAD_FAIL";
export const SET_SERVICE_POST_SERVICE_URL =
  "/ServicePostService/ServiceCreditCartPaymentSuccess";

export const GET_READ_QR_CODE = "SERVICE_SCREEN/GET_READ_QR_CODE/LOAD";
export const GET_READ_QR_CODE_SUCCESS =
  "SERVICE_SCREEN/GET_READ_QR_CODE/LOAD_SUCCESS";
export const GET_READ_QR_CODE_FAIL =
  "SERVICE_SCREEN/GET_READ_QR_CODE/LOAD_FAIL";
export const GET_READ_QR_CODE_URL = "/ServicePostService/ReadQrCode";

export const POST_SERVICE_COMPLAINT =
  "SERVICE_SCREEN/POST_SERVICE_COMPLAINT/LOAD";
export const POST_SERVICE_COMPLAINT_SUCCESS =
  "SERVICE_SCREEN/POST_SERVICE_COMPLAINT/LOAD_SUCCESS";
export const POST_SERVICE_COMPLAINT_FAIL =
  "SERVICE_SCREEN/GET_READ_QR_CODE/LOAD_FAIL";
export const POST_SERVICE_COMPLAINT_URL =
  "/ServicePostService/ServiceComplaint";
