export const SET_SERVICE_CREATE = "SERVICE_SCREEN/SET_SERVICE_CREATE/LOAD";
export const SET_SERVICE_CREATE_SUCCESS =
  "SERVICE_SCREEN/SET_SERVICE_CREATE/LOAD_SUCCESS";
export const SET_SERVICE_CREATE_FAIL =
  "SERVICE_SCREEN/SET_SERVICE_CREATE/LOAD_FAIL";
export const SET_SERVICE_CREATE_URL = "/ServiceService/CreateService"; 