export const GET_SERVICE_CREATE_DATA =
  "SERVICE_SCREEN/GET_SERVICE_CREATE_DATA/LOAD";
export const GET_SERVICE_CREATE_DATA_SUCCESS =
  "SERVICE_SCREEN/GET_SERVICE_CREATE_DATA/LOAD_SUCCESS";
export const GET_SERVICE_CREATE_DATA_FAIL =
  "SERVICE_SCREEN/GET_SERVICE_CREATE_DATA/LOAD_FAIL";
export const GET_SERVICE_CREATE_DATA_URL = "/ServiceService/CategoryService"; 

export const SET_USER_CHAT_MESSAGE_OLD =
  "CHAT_SCREEN/SET_USER_CHAT_MESSAGE_OLD/LOAD";
export const SET_USER_CHAT_MESSAGE_OLD_SUCCESS =
  "CHAT_SCREEN/SET_USER_CHAT_MESSAGE_OLD/LOAD_SUCCESS";
export const SET_USER_CHAT_MESSAGE_OLD_FAIL =
  "CHAT_SCREEN/SET_USER_CHAT_MESSAGE_OLD/LOAD_FAIL";
export const SET_USER_CHAT_MESSAGE_OLD_URL = "/ServiceService/OldChatData";

export const GET_PROPOSAL_DETAIL =
  "COMPANY_SERVICE_SCREEN/GET_PROPOSAL_DETAIL/LOAD";
export const GET_PROPOSAL_DETAIL_SUCCESS =
  "COMPANY_SERVICE_SCREEN/GET_PROPOSAL_DETAIL/LOAD_SUCCESS";
export const GET_PROPOSAL_DETAIL_FAIL =
  "COMPANY_SERVICE_SCREEN/GET_PROPOSAL_DETAIL/LOAD_FAIL";
export const GET_PROPOSAL_DETAIL_URL = "/ServiceService/ProposalDetail";

export const UPDATE_PROPOSAL_PRICE =
  "COMPANY_SERVICE_SCREEN/UPDATE_PROPOSAL_PRICE/LOAD";
export const UPDATE_PROPOSAL_PRICE_SUCCESS =
  "COMPANY_SERVICE_SCREEN/UPDATE_PROPOSAL_PRICE/LOAD_SUCCESS";
export const UPDATE_PROPOSAL_PRICE_FAIL =
  "COMPANY_SERVICE_SCREEN/UPDATE_PROPOSAL_PRICE/LOAD_FAIL";
export const UPDATE_PROPOSAL_PRICE_URL =
  "/ServicePostService/UpdateServiceProposal";
