export const GET_SERVICE_CREATE_DATA =
  "SERVICE_SCREEN/GET_SERVICE_CREATE_DATA/LOAD";
export const GET_SERVICE_CREATE_DATA_SUCCESS =
  "SERVICE_SCREEN/GET_SERVICE_CREATE_DATA/LOAD_SUCCESS";
export const GET_SERVICE_CREATE_DATA_FAIL =
  "SERVICE_SCREEN/GET_SERVICE_CREATE_DATA/LOAD_FAIL";
export const GET_SERVICE_CREATE_DATA_URL = "/ServiceService/CategoryService";

export const SET_USER_CHAT_MESSAGE_OLD =
  "CHAT_SCREEN/SET_USER_CHAT_MESSAGE_OLD/LOAD";
export const SET_USER_CHAT_MESSAGE_OLD_SUCCESS =
  "CHAT_SCREEN/SET_USER_CHAT_MESSAGE_OLD/LOAD_SUCCESS";
export const SET_USER_CHAT_MESSAGE_OLD_FAIL =
  "CHAT_SCREEN/SET_USER_CHAT_MESSAGE_OLD/LOAD_FAIL";
export const SET_USER_CHAT_MESSAGE_OLD_URL = "/ServiceService/OldChatData";

export const GET_PROPOSAL_DETAIL =
  "COMPANY_SERVICE_SCREEN/GET_PROPOSAL_DETAIL/LOAD";
export const GET_PROPOSAL_DETAIL_SUCCESS =
  "COMPANY_SERVICE_SCREEN/GET_PROPOSAL_DETAIL/LOAD_SUCCESS";
export const GET_PROPOSAL_DETAIL_FAIL =
  "COMPANY_SERVICE_SCREEN/GET_PROPOSAL_DETAIL/LOAD_FAIL";
export const GET_PROPOSAL_DETAIL_URL = "/ServiceService/ProposalDetail";

export const UPDATE_PROPOSAL_PRICE =
  "COMPANY_SERVICE_SCREEN/UPDATE_PROPOSAL_PRICE/LOAD";
export const UPDATE_PROPOSAL_PRICE_SUCCESS =
  "COMPANY_SERVICE_SCREEN/UPDATE_PROPOSAL_PRICE/LOAD_SUCCESS";
export const UPDATE_PROPOSAL_PRICE_FAIL =
  "COMPANY_SERVICE_SCREEN/UPDATE_PROPOSAL_PRICE/LOAD_FAIL";
export const UPDATE_PROPOSAL_PRICE_URL =
  "/ServicePostService/UpdateServiceProposal";

export const GET_SERVICE_CUSTOMER_PAGE =
  "COMPANY_SERVICE_SCREEN/GET_SERVICE_CUSTOMER_PAGE/LOAD";
export const GET_SERVICE_CUSTOMER_PAGE_SUCCESS =
  "COMPANY_SERVICE_SCREEN/GET_SERVICE_CUSTOMER_PAGE/LOAD_SUCCESS";
export const GET_SERVICE_CUSTOMER_PAGE_FAIL =
  "COMPANY_SERVICE_SCREEN/GET_SERVICE_CUSTOMER_PAGE/LOAD_FAIL";
export const GET_SERVICE_CUSTOMER_PAGE_URL =
  "/ServiceService/GetServiceCustomerPage";

export const GET_SERVICE_COMPANY_PAGE =
  "COMPANY_SERVICE_SCREEN/GET_SERVICE_COMPANY_PAGE/LOAD";
export const GET_SERVICE_COMPANY_PAGE_SUCCESS =
  "COMPANY_SERVICE_SCREEN/GET_SERVICE_COMPANY_PAGE/LOAD_SUCCESS";
export const GET_SERVICE_COMPANY_PAGE_FAIL =
  "COMPANY_SERVICE_SCREEN/GET_SERVICE_COMPANY_PAGE/LOAD_FAIL";
export const GET_SERVICE_COMPANY_PAGE_URL =
  "/ServiceService/GetServicesCompanyPage";

export const GET_MASTER_SERVICE_PROPOSAL_QUESTION_PAGE =
  "COMPANY_SERVICE_SCREEN/GET_MASTER_SERVICE_PROPOSAL_QUESTION_PAGE/LOAD";
export const GET_MASTER_SERVICE_PROPOSAL_QUESTION_PAGE_SUCCESS =
  "COMPANY_SERVICE_SCREEN/GET_MASTER_SERVICE_PROPOSAL_QUESTION_PAGE/LOAD_SUCCESS";
export const GET_MASTER_SERVICE_PROPOSAL_QUESTION_PAGE_FAIL =
  "COMPANY_SERVICE_SCREEN/GET_MASTER_SERVICE_PROPOSAL_QUESTION_PAGE/LOAD_FAIL";
export const GET_MASTER_SERVICE_PROPOSAL_QUESTION_PAGE_URL =
  "/ServiceService/GetMasterServiceProposalQuestion";

export const POST_SERVICE_SEND_PROPOSAL =
  "COMPANY_SERVICE_SCREEN/POST_SERVICE_SEND_PROPOSAL/LOAD";
export const POST_SERVICE_SEND_PROPOSAL_SUCCESS =
  "COMPANY_SERVICE_SCREEN/POST_SERVICE_SEND_PROPOSAL/LOAD_SUCCESS";
export const POST_SERVICE_SEND_PROPOSAL_FAIL =
  "COMPANY_SERVICE_SCREEN/POST_SERVICE_SEND_PROPOSAL/LOAD_FAIL";
export const POST_SERVICE_SEND_PROPOSAL_URL =
  "/ServiceService/ServiceSendProposal";

export const GET_SERVICE_PROPOSAL_PREVIEW =
  "COMPANY_SERVICE_SCREEN/GET_SERVICE_PROPOSAL_PREVIEW/LOAD";
export const GET_SERVICE_PROPOSAL_PREVIEW_SUCCESS =
  "COMPANY_SERVICE_SCREEN/GET_SERVICE_PROPOSAL_PREVIEW/LOAD_SUCCESS";
export const GET_SERVICE_PROPOSAL_PREVIEW_FAIL =
  "COMPANY_SERVICE_SCREEN/GET_SERVICE_PROPOSAL_PREVIEW/LOAD_FAIL";
export const GET_SERVICE_PROPOSAL_PREVIEW_URL =
  "/ServiceService/ServiceProposalPreview";
