export const GET_POPULAR_CATEGORIES = 'HOME_SCREEN/POPULAR_CATEGORIES/LOAD';
export const GET_POPULAR_CATEGORIES_SUCCESS = 'HOME_SCREEN/POPULAR_CATEGORIES/LOAD_SUCCESS';
export const GET_POPULAR_CATEGORIES_FAIL = 'HOME_SCREEN/POPULAR_CATEGORIES/LOAD_FAIL';
export const GET_POPULAR_CATEGORIES_URL = '/HomeService/ServiceCategoryList';

export const GET_SEARCH_CATEGORIES = 'HOME_SCREEN/SEARCH_CATEGORIES/LOAD';
export const GET_SEARCH_CATEGORIES_SUCCESS = 'HOME_SCREEN/SEARCH_CATEGORIES/LOAD_SUCCESS';
export const GET_SEARCH_CATEGORIES_FAIL = 'HOME_SCREEN/SEARCH_CATEGORIES/LOAD_FAIL';
export const GET_SEARCH_CATEGORIES_URL = '/HomeService/SearchCategory';

export const GET_TOKEN = 'GENERAL_SETTINGS/GET_TOKEN/LOAD';
export const GET_TOKEN_SUCCESS = 'GENERAL_SETTINGS/GET_TOKEN/LOAD_SUCCESS';
export const GET_TOKEN_FAIL = 'GENERAL_SETTINGS/GET_TOKEN/LOAD_FAIL';
export const GET_TOKEN_URL = '/GeneralServiceGet/getToken';

export const GET_CATEGORIES_AND_SUBCATEGORIES = 'HOME_SCREEN/GET_CATEGORIES_AND_SUBCATEGORIES/LOAD';
export const GET_CATEGORIES_AND_SUBCATEGORIES_SUCCESS = 'HOME_SCREEN/GET_CATEGORIES_AND_SUBCATEGORIES/LOAD_SUCCESS';
export const GET_CATEGORIES_AND_SUBCATEGORIES_FAIL = 'HOME_SCREEN/GET_CATEGORIES_AND_SUBCATEGORIES/LOAD_FAIL';
export const GET_CATEGORIES_AND_SUBCATEGORIES_URL = '/CategoryService/AllCategoriesAndSubCategories';

export const GET_SERVICE_CREATE_DATA = 'SERVICE_SCREEN/GET_SERVICE_CREATE_DATA/LOAD';
export const GET_SERVICE_CREATE_DATA_SUCCESS = 'SERVICE_SCREEN/GET_SERVICE_CREATE_DATA/LOAD_SUCCESS';
export const GET_SERVICE_CREATE_DATA_FAIL = 'SERVICE_SCREEN/GET_SERVICE_CREATE_DATA/LOAD_FAIL';
export const GET_SERVICE_CREATE_DATA_URL = '/ServiceService/CategoryService';

export const SET_SERVICE_CREATE = 'SERVICE_SCREEN/SET_SERVICE_CREATE/LOAD';
export const SET_SERVICE_CREATE_SUCCESS = 'SERVICE_SCREEN/SET_SERVICE_CREATE/LOAD_SUCCESS';
export const SET_SERVICE_CREATE_FAIL = 'SERVICE_SCREEN/SET_SERVICE_CREATE/LOAD_FAIL';
export const SET_SERVICE_CREATE_URL = '/ServiceService/CreateService';

export const GET_CUSTOMER_SERVICE_COUNT = 'CUSTOMER_DETAIL_SCREEN/GET_CUSTOMER_SERVICE_COUNT/LOAD';
export const GET_CUSTOMER_SERVICE_COUNT_SUCCESS = 'CUSTOMER_DETAIL_SCREEN/GET_CUSTOMER_SERVICE_COUNT/LOAD_SUCCESS';
export const GET_CUSTOMER_SERVICE_COUNT_FAIL = 'CUSTOMER_DETAIL_SCREEN/GET_CUSTOMER_SERVICE_COUNT/LOAD_FAIL';
export const GET_CUSTOMER_SERVICE_COUNT_URL = '/CustomerDetailService/CustomerServiceCount';

export const SET_USER_UPDATE = 'CUSTOMER_DETAIL_PROFILE_SCREEN/SET_USER_UPDATE/LOAD';
export const SET_USER_UPDATE_SUCCESS = 'CUSTOMER_DETAIL_PROFILE_SCREEN/SET_USER_UPDATE/LOAD_SUCCESS';
export const SET_USER_UPDATE_FAIL = 'CUSTOMER_DETAIL_PROFILE_SCREEN/SET_USER_UPDATE/LOAD_FAIL';
export const SET_USER_UPDATE_URL = '/CustomerDetailService/editUserInformation';

export const SET_CUSTOMER_UPDATE = 'CUSTOMER_DETAIL_PROFILE_SCREEN/SET_CUSTOMER_UPDATE/LOAD';
export const SET_CUSTOMER_UPDATE_SUCCESS = 'CUSTOMER_DETAIL_PROFILE_SCREEN/SET_CUSTOMER_UPDATE/LOAD_SUCCESS';
export const SET_CUSTOMER_UPDATE_FAIL = 'CUSTOMER_DETAIL_PROFILE_SCREEN/SET_CUSTOMER_UPDATE/LOAD_FAIL';
export const SET_CUSTOMER_UPDATE_URL = '/CustomerDetailService/editCustomerInformation';

export const REFRESH_AUTHENTICATION_USER = 'ALL_SCREEN/REFRESH_AUTHENTICATION_USER/LOAD';
export const REFRESH_AUTHENTICATION_USER_SUCCESS = 'ALL_SCREEN/REFRESH_AUTHENTICATION_USER/LOAD_SUCCESS';
export const REFRESH_AUTHENTICATION_USER_FAIL = 'ALL_SCREEN/REFRESH_AUTHENTICATION_USER/LOAD_FAIL';
export const REFRESH_AUTHENTICATION_USER_URL = '/GeneralServiceGet/GetActiveUserView';

export const GET_USER_MESSAGE_LIST = 'CHAT_SCREEN/GET_USER_MESSAGE_LIST/LOAD';
export const GET_USER_MESSAGE_LIST_SUCCESS = 'CHAT_SCREEN/GET_USER_MESSAGE_LIST/LOAD_SUCCESS';
export const GET_USER_MESSAGE_LIST_FAIL = 'CHAT_SCREEN/GET_USER_MESSAGE_LIST/LOAD_FAIL';
export const GET_USER_MESSAGE_LIST_URL = '/MessageServiceGet/GetChatList';

export const POST_USER_CHAT_READ_MESSAGE = 'CHAT_SCREEN/POST_USER_CHAT_READ_MESSAGE/LOAD';
export const POST_USER_CHAT_READ_MESSAGE_SUCCESS = 'CHAT_SCREEN/POST_USER_CHAT_READ_MESSAGE/LOAD_SUCCESS';
export const POST_USER_CHAT_READ_MESSAGE_FAIL = 'CHAT_SCREEN/POST_USER_CHAT_READ_MESSAGE/LOAD_FAIL';
export const POST_USER_CHAT_READ_MESSAGE_URL = '/MessageServicePost/userChatReading';

export const SET_USER_CHAT_MESSAGE_OLD = 'CHAT_SCREEN/SET_USER_CHAT_MESSAGE_OLD/LOAD';
export const SET_USER_CHAT_MESSAGE_OLD_SUCCESS = 'CHAT_SCREEN/SET_USER_CHAT_MESSAGE_OLD/LOAD_SUCCESS';
export const SET_USER_CHAT_MESSAGE_OLD_FAIL = 'CHAT_SCREEN/SET_USER_CHAT_MESSAGE_OLD/LOAD_FAIL';
export const SET_USER_CHAT_MESSAGE_OLD_URL = '/ServiceService/OldChatData';

export const GET_CONTACT_MESSAGE_SUBJECT = 'CONTACT_SCREEN/GET_CONTACT_MESSAGE_SUBJECT/LOAD';
export const GET_CONTACT_MESSAGE_SUBJECT_SUCCESS = 'CONTACT_SCREEN/GET_CONTACT_MESSAGE_SUBJECT/LOAD_SUCCESS';
export const GET_CONTACT_MESSAGE_SUBJECT_FAIL = 'CONTACT_SCREEN/GET_CONTACT_MESSAGE_SUBJECT/LOAD_FAIL';
export const GET_CONTACT_MESSAGE_SUBJECT_URL = '/HomeService/MessageSubjectList';

export const POST_CONTACT_MESSAGE = 'CONTACT_SCREEN/POST_CONTACT_MESSAGE/LOAD';
export const POST_CONTACT_MESSAGE_SUCCESS = 'CONTACT_SCREEN/POST_CONTACT_MESSAGE/LOAD_SUCCESS';
export const POST_CONTACT_MESSAGE_FAIL = 'CONTACT_SCREEN/POST_CONTACT_MESSAGE/LOAD_FAIL';
export const POST_CONTACT_MESSAGE_URL = '/HomeService/AddToNewContactMessage';

export const GET_COMPANY_SERVICE_PREVIVEW = 'COMPANY_SERVICE_SCREEN/GET_COMPANY_SERVICE_PREVIVEW/LOAD';
export const GET_COMPANY_SERVICE_PREVIVEW_SUCCESS = 'COMPANY_SERVICE_SCREEN/GET_COMPANY_SERVICE_PREVIVEW/LOAD_SUCCESS';
export const GET_COMPANY_SERVICE_PREVIVEW_FAIL = 'COMPANY_SERVICE_SCREEN/GET_COMPANY_SERVICE_PREVIVEW/LOAD_FAIL';
export const GET_COMPANY_SERVICE_PREVIVEW_URL = '/CompanyDetailService/CompanyServicePreviewView';

export const GET_SERVICE_PREVIEW_DETAIL = 'ALL_SCREEN/GET_SERVICE_PREVIEW_DETAIL/LOAD';
export const GET_SERVICE_PREVIEW_DETAIL_SUCCESS = 'ALL_SCREEN/GET_SERVICE_PREVIEW_DETAIL/LOAD_SUCCESS';
export const GET_SERVICE_PREVIEW_DETAIL_FAIL = 'ALL_SCREEN/GET_SERVICE_PREVIEW_DETAIL/LOAD_FAIL';
export const GET_SERVICE_PREVIEW_DETAIL_URL = '/CustomerDetailService/servicePreviewObjs';

export const GET_SERVICE_PREVIEW_DETAIL_QUESTION = 'ALL_SCREEN/GET_SERVICE_PREVIEW_DETAIL_QUESTION/LOAD';
export const GET_SERVICE_PREVIEW_DETAIL_QUESTION_SUCCESS = 'ALL_SCREEN/GET_SERVICE_PREVIEW_DETAIL_QUESTION/LOAD_SUCCESS';
export const GET_SERVICE_PREVIEW_DETAIL_QUESTION_FAIL = 'ALL_SCREEN/GET_SERVICE_PREVIEW_DETAIL_QUESTION/LOAD_FAIL';
export const GET_SERVICE_PREVIEW_DETAIL_QUESTION_URL = '/CustomerDetailService/ServiceCategoryQuestionsAndAnswers';

export const LOGOUT_USER = 'ALL_SCREEN/LOGOUT_USER/LOAD';
export const LOGOUT_USER_SUCCESS = 'ALL_SCREEN/LOGOUT_USER/LOAD_SUCCESS';
export const LOGOUT_USER_FAIL = 'ALL_SCREEN/LOGOUT_USER/LOAD_FAIL';
export const LOGOUT_USER_URL = '';

export const LOGIN_USER = 'ALL_SCREEN/LOGIN_USER/LOAD';
export const LOGIN_USER_SUCCESS = 'ALL_SCREEN/LOGIN_USER/LOAD_SUCCESS';
export const LOGIN_USER_FAIL = 'ALL_SCREEN/LOGIN_USER/LOAD_FAIL';
export const LOGIN_USER_URL = '/GeneralServiceGet/GetActiveUserView';

export const GET_PROPOSAL_DETAIL = 'COMPANY_SERVICE_SCREEN/GET_PROPOSAL_DETAIL/LOAD';
export const GET_PROPOSAL_DETAIL_SUCCESS = 'COMPANY_SERVICE_SCREEN/GET_PROPOSAL_DETAIL/LOAD_SUCCESS';
export const GET_PROPOSAL_DETAIL_FAIL = 'COMPANY_SERVICE_SCREEN/GET_PROPOSAL_DETAIL/LOAD_FAIL';
export const GET_PROPOSAL_DETAIL_URL = '/ServiceService/ProposalDetail';

export const UPDATE_PROPOSAL_PRICE = 'COMPANY_SERVICE_SCREEN/UPDATE_PROPOSAL_PRICE/LOAD';
export const UPDATE_PROPOSAL_PRICE_SUCCESS = 'COMPANY_SERVICE_SCREEN/UPDATE_PROPOSAL_PRICE/LOAD_SUCCESS';
export const UPDATE_PROPOSAL_PRICE_FAIL = 'COMPANY_SERVICE_SCREEN/UPDATE_PROPOSAL_PRICE/LOAD_FAIL';
export const UPDATE_PROPOSAL_PRICE_URL = '/ServicePostService/UpdateServiceProposal';

export const GET_CUSTOMER_SERVICE_PREVIVEW = 'CUSTOMER_SERVICE_SCREEN/GET_CUSTOMER_SERVICE_PREVIVEW/LOAD';
export const GET_CUSTOMER_SERVICE_PREVIVEW_SUCCESS = 'CUSTOMER_SERVICE_SCREEN/GET_CUSTOMER_SERVICE_PREVIVEW/LOAD_SUCCESS';
export const GET_CUSTOMER_SERVICE_PREVIVEW_FAIL = 'CUSTOMER_SERVICE_SCREEN/GET_CUSTOMER_SERVICE_PREVIVEW/LOAD_FAIL';
export const GET_CUSTOMER_SERVICE_PREVIVEW_URL = '/CustomerDetailService/ServicePreview';